//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4ISP9_18VB_FEDIN_NESMELOV_Clothing_Store.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public string OrderDate { get; set; }
        public int ClientID { get; set; }
        public int EmployeeID { get; set; }
        public int ClothingID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Clothing Clothing { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual OrderInfo OrderInfo { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
    }
}
