//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4ISP9_18VB_FEDIN_NESMELOV_Clothing_Store.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatus
    {
        public int OrderID { get; set; }
        public int EmployeeID { get; set; }
        public int ClothingID { get; set; }
        public int OrderInfoID { get; set; }
        public int Count { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual OrderInfo OrderInfo { get; set; }
    }
}
